--- #YAML:1.0
name: VMware-vCloud
abstract: VMware vCloud API
version: VERSIONTAG0
author:
 - Phillip Pollard <bennie@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.005_03
  Cache::Bounded: 1.05
  Data::Dumper: 0
  LWP: 5
  XML::Simple: 2
build_requires:
  Test: 0
resources:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: hand
provides:
  VMware::vCloud:
    file: lib/VMware/vCloud.pm
    version: VERSIONTAG
  VMware::API::vCloud:
    file: lib/VMware/API/vCloud.pm
    version: VERSIONTAG

